version: "2"

linters:
  default: none
  enable:
    - govet
    - misspell
    - gocyclo
    - ineffassign
    - staticcheck
  settings:
    gocyclo:
      min-complexity: 15

formatters:
  enable:
    - gofmt
